### ISSUE TITLE
关于在线体验

### ISSUE THREAD

**Issue by ai1li1er1** [AndersonBY/vector-vein#1]
想请问一下为什么在线体验的链接打不开，谢谢

**Comment by AndersonBY** [comment]
正常的呀目前：https://vectorvein.com/

**Comment by ai1li1er1** [comment]
能打开了，但注册又出了点小问题，反复要验证邮箱，点了邮件里的验证地址还是弹出验证邮箱

**Comment by AndersonBY** [comment]
验证链接你发出来我看看

**Comment by ai1li1er1** [comment]
https://vectorvein.com/email/verify/1544416986a1459bbaee6dfd94a5791c?signature=0aa3cd2789f61ed0ceeddd5784861966

**Comment by AndersonBY** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/5e5e315a-61c3-4066-8e5b-2c0414c0b079)
我帮你打开这个链接后验证成功了🤣，能不能说一下你是用什么打开连接的？是邮箱里直接打开的吗？

**Comment by ai1li1er1** [comment]
多谢！我是直接在邮箱点开不行，复制链接到地址栏也不行，开着梯子关了梯子都不行，用的edge

**Comment by AndersonBY** [comment]
我还真没在Edge上测试过，感谢反馈

**Comment by jchenibm** [comment]
我也用一样的问题，反复要求邮箱验证。

我的验证链接：
https://vectorvein.com/email/verify/aa93dfaf76f947feb94edf3735ca0e16?signature=ac75b88e872ff2d8cda52454bc2b90a6

**Comment by AndersonBY** [comment]
> 我也用一样的问题，反复要求邮箱验证。
> 
> 我的验证链接： https://vectorvein.com/email/verify/aa93dfaf76f947feb94edf3735ca0e16?signature=ac75b88e872ff2d8cda52454bc2b90a6

这个问题刚刚中午修复了，是我前端没写好
