### ISSUE TITLE
希望增加OpenAI API地址设置

### ISSUE THREAD

**Issue by s544838371** [AndersonBY/vector-vein#10]
如标题所示

**Comment by AndersonBY** [comment]
具体的文档提供一下

**Comment by s544838371** [comment]
> 具体的文档提供一下

麻了，我还真不知道提供啥，咋实现的，我说一下我的具体意思吧
"api_url": API的URL地址，OpenAI的是 https://api.openai.com
但是该地址在本机访问的时候需要你能不墙才行，但是大部分情况下都是被墙的
所以希望修改这个默认API的URL地址
我能提供几个开源项目，这几个开源项目里有配置API地址的地方，如下所示：
1. https://github.com/easychen/chatchan-dist
2. https://github.com/openai-translator/openai-translator
3. https://github.com/excing/chatgpt
然后还有个
1.https://github.com/noobnooc/noobnooc/discussions/9

**Comment by AndersonBY** [comment]
害，光看你标题也不知道说改哪的。你就是说改backend/worker/tasks/llms.py里面的openai.api_base = "https://api.openai.com/v1"这个是吧

**Comment by s544838371** [comment]
> 害，光看你标题也不知道说改哪的。你就是说改backend/worker/tasks/llms.py里面的openai.api_base = "[https://api.openai.com/v1"这个是吧](https://api.openai.com/v1%22%E8%BF%99%E4%B8%AA%E6%98%AF%E5%90%A7)

对，我以为大家都知道，我的锅

**Comment by AndersonBY** [comment]
[https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip](https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip)

v0.0.5已添加指定非官方API BASE设置。

**Comment by s544838371** [comment]
> [`v0.0.5` vector-vein-windows.zip (download)](https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip)
> 
> v0.0.5已添加指定非官方API BASE设置。

@AndersonBY 大佬你打包Release的时候zip能不能加上版本号

**Comment by AndersonBY** [comment]
可以

**Comment by s544838371** [comment]
> 可以

感谢！
