### ISSUE TITLE
功能建议：增加一个“列表选项"输入构件

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#16]
有时，希望用户是在一系列选项中进行选择，因此希望能够预先定义好一个选项列表，供用户选。
如：
1、代码解释
2、代码纠错
3、代码试运行

在输出时，可以有两种选择：
单选或多选。

**Comment by AndersonBY** [comment]
这个应该要有，我最近设计一下

**Comment by AndersonBY** [comment]
已经添加到文本合成节点里了，添加变量时可以选择列表输入
