### ISSUE TITLE
报错：软件打包后，执行报错：no module name 'webview"

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#19]
在pdm run build后，执行dist 目录下的 VectorVein.exe 命令后，报如下错误。

![image](https://github.com/AndersonBY/vector-vein/assets/45526589/ff4a46dd-54f7-42da-82ba-f8cbca6f8150)

这是dist/vector-vein目录下的文件列表：
目录: D:\vector-vein-dev\vector-vein\backend\dist\vector-vein

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/6/17     20:45                web
-a----         2023/6/17     20:45        1847603 base_library.zip
-a----          2023/6/7      6:02        3445016 libcrypto-1_1.dll
-a----          2023/6/7      6:02         704792 libssl-1_1.dll
-a----          2023/6/7      6:01        5762840 python311.dll
-a----          2023/6/7      6:01          30480 select.pyd
-a----          2023/6/7      6:01        1141016 unicodedata.pyd
-a----          2023/6/7      6:02         109392 VCRUNTIME140.dll
-a----         2023/6/17     20:45        2015004 VectorVein.exe
-a----         2023/6/17     20:45              5 version.txt
-a----          2023/6/7      6:01          84760 _bz2.pyd
-a----          2023/6/7      6:01         253200 _decimal.pyd
-a----          2023/6/7      6:01          65304 _hashlib.pyd
-a----          2023/6/7      6:01         158992 _lzma.pyd
-a----          2023/6/7      6:01          32528 _queue.pyd
-a----          2023/6/7      6:01          79640 _socket.pyd
-a----          2023/6/7      6:01         161040 _ssl.pyd
-a----          2023/6/7      6:01          25360 _uuid.pyd

确实没有 webview目录。不知是不是安装 webview2的问题。

我下载你提供的安装版本，能够正常启动，且在下面发现有 webview目录，如下所示：
![image](https://github.com/AndersonBY/vector-vein/assets/45526589/c8996a72-a7f0-4c4c-8a9d-759215289b3a)

**Comment by AndersonBY** [comment]
那看来是打包的问题，再试一下打包，注意看看打包的时候报错或者提示信息是啥

**Comment by jiangfangfangxm** [comment]
下面是执行命令的输出：
PS D:\vector-vein-dev\vector-vein\backend> pdm run build
343 INFO: PyInstaller: 5.12.0
343 INFO: Python: 3.11.4
375 INFO: Platform: Windows-10-10.0.22621-SP0
375 INFO: UPX is not available.
390 INFO: Extending PYTHONPATH with paths
['D:\\vector-vein-dev\\vector-vein\\backend']
711 INFO: Appending 'datas' from .spec
726 INFO: checking Analysis
726 INFO: Building because D:\vector-vein-dev\vector-vein\backend\web\assets\AccountInfo-cec1c748.js changed
726 INFO: Initializing module dependency graph...
726 INFO: Caching module graph hooks...
742 INFO: Analyzing base_library.zip ...
2915 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
2993 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
4774 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
6448 INFO: Caching module dependency graph...
6558 INFO: running Analysis Analysis-00.toc
6558 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Python311\python.exe
6651 INFO: Analyzing D:\vector-vein-dev\vector-vein\backend\main.py
6792 INFO: Loading module hook 'hook-platform.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
7120 INFO: Analyzing hidden import 'tiktoken_ext.openai_public'
7120 ERROR: Hidden import 'tiktoken_ext.openai_public' not found
7120 INFO: Analyzing hidden import 'tiktoken_ext'
7120 ERROR: Hidden import 'tiktoken_ext' not found
7120 INFO: Processing module hooks...
7136 INFO: Looking for ctypes DLLs
7151 INFO: Analyzing run-time hooks ...
7151 INFO: Including run-time hook 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
7151 INFO: Looking for dynamic libraries
344 INFO: Extra DLL search directories (AddDllDirectory): []
344 INFO: Extra DLL search directories (PATH): ['D:\\vector-vein-dev\\vector-vein\\backend\\.venv\\Scripts', 'C:\\Python311\\Scripts\\', 'C:\\Python311\\', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\Program Files\\Calibre2\\', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files\\Docker\\Docker\\resources\\bin', 'C:\\ProgramData\\DockerDesktop\\version-bin', 'C:\\Program Files\\Chez Scheme 9.5.8\\bin\\ta6nt', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\nodejs\\', 'C:\\Users\\jiangfangfang\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\jiangfangfang\\AppData\\Local\\Programs\\Microsoft VS Code\\bin', 'C:\\Users\\jiangfangfang\\AppData\\Local\\GitHubDesktop\\bin', 'C:\\Users\\jiangfangfang\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\jiangfangfang\\AppData\\Roaming\\npm', 'c:\\users\\jiangfangfang\\appdata\\roaming\\python\\python311\\scripts', 'c:\\users\\jiangfangfang\\.local\\bin', 'D:\\vector-vein-dev\\vector-vein\\backend\\.venv\\Scripts']
8101 INFO: Looking for eggs
8101 INFO: Using Python library C:\Python311\python311.dll
8101 INFO: Found binding redirects:
[]
8105 INFO: Warnings written to D:\vector-vein-dev\vector-vein\backend\build\main\warn-main.txt
8121 INFO: Graph cross-reference written to D:\vector-vein-dev\vector-vein\backend\build\main\xref-main.html
8136 INFO: checking PYZ
8152 INFO: checking PKG
8152 INFO: Bootloader C:\Python311\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
8152 INFO: checking EXE
8152 INFO: checking COLLECT
8152 INFO: Removing dir D:\vector-vein-dev\vector-vein\backend\dist\vector-vein
8199 INFO: Building COLLECT COLLECT-00.toc
8324 INFO: Building COLLECT COLLECT-00.toc completed successfully.
PS D:\vector-vein-dev\vector-vein\backend>

**Comment by AndersonBY** [comment]
把dist和build文件夹删了重新build一下试试

**Comment by jiangfangfangxm** [comment]
执行了删除操作，好象仍然没有生成 webview目录。运行时，仍然报一样的错误：no module name 'webview'

PS D:\vector-vein-dev\vector-vein\backend> rm  build

确认
D:\vector-vein-dev\vector-vein\backend\build 处的项具有子项，并且未指定 Recurse
参数。如果继续，所有子项均将随该项删除。是否确实要继续?
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“Y”): y
PS D:\vector-vein-dev\vector-vein\backend> rm dist

确认
D:\vector-vein-dev\vector-vein\backend\dist 处的项具有子项，并且未指定 Recurse
参数。如果继续，所有子项均将随该项删除。是否确实要继续?
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“Y”): y
PS D:\vector-vein-dev\vector-vein\backend> pdm run build
354 INFO: PyInstaller: 5.12.0
354 INFO: Python: 3.11.4
383 INFO: Platform: Windows-10-10.0.22621-SP0
388 INFO: UPX is not available.
390 INFO: Extending PYTHONPATH with paths
['D:\\vector-vein-dev\\vector-vein\\backend']
727 INFO: Appending 'datas' from .spec
731 INFO: checking Analysis
732 INFO: Building Analysis because Analysis-00.toc is non existent
732 INFO: Initializing module dependency graph...
734 INFO: Caching module graph hooks...
753 INFO: Analyzing base_library.zip ...
3442 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
3544 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
5333 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
7073 INFO: Caching module dependency graph...
7171 INFO: running Analysis Analysis-00.toc
7176 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Python311\python.exe
7266 INFO: Analyzing D:\vector-vein-dev\vector-vein\backend\main.py
7419 INFO: Loading module hook 'hook-platform.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
7742 INFO: Analyzing hidden import 'tiktoken_ext.openai_public'
7743 ERROR: Hidden import 'tiktoken_ext.openai_public' not found
7744 INFO: Analyzing hidden import 'tiktoken_ext'
7745 ERROR: Hidden import 'tiktoken_ext' not found
7745 INFO: Processing module hooks...
7754 INFO: Looking for ctypes DLLs
7765 INFO: Analyzing run-time hooks ...
7767 INFO: Including run-time hook 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
7773 INFO: Looking for dynamic libraries
375 INFO: Extra DLL search directories (AddDllDirectory): []
375 INFO: Extra DLL search directories (PATH): ['D:\\vector-vein-dev\\vector-vein\\backend\\.venv\\Scripts', 'C:\\Python311\\Scripts\\', 'C:\\Python311\\', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\Program Files\\Calibre2\\', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files\\Docker\\Docker\\resources\\bin', 'C:\\ProgramData\\DockerDesktop\\version-bin', 'C:\\Program Files\\Chez Scheme 9.5.8\\bin\\ta6nt', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\nodejs\\', 'C:\\Users\\jiangfangfang\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\jiangfangfang\\AppData\\Local\\Programs\\Microsoft VS Code\\bin', 'C:\\Users\\jiangfangfang\\AppData\\Local\\GitHubDesktop\\bin', 'C:\\Users\\jiangfangfang\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\jiangfangfang\\AppData\\Roaming\\npm', 'c:\\users\\jiangfangfang\\appdata\\roaming\\python\\python311\\scripts', 'c:\\users\\jiangfangfang\\.local\\bin', 'D:\\vector-vein-dev\\vector-vein\\backend\\.venv\\Scripts']
8777 INFO: Looking for eggs
8778 INFO: Using Python library C:\Python311\python311.dll
8778 INFO: Found binding redirects:
[]
8782 INFO: Warnings written to D:\vector-vein-dev\vector-vein\backend\build\main\warn-main.txt
8806 INFO: Graph cross-reference written to D:\vector-vein-dev\vector-vein\backend\build\main\xref-main.html
8827 INFO: checking PYZ
8827 INFO: Building PYZ because PYZ-00.toc is non existent
8828 INFO: Building PYZ (ZlibArchive) D:\vector-vein-dev\vector-vein\backend\build\main\PYZ-00.pyz
9132 INFO: Building PYZ (ZlibArchive) D:\vector-vein-dev\vector-vein\backend\build\main\PYZ-00.pyz completed successfully.
9137 INFO: checking PKG
9137 INFO: Building PKG because PKG-00.toc is non existent
9137 INFO: Building PKG (CArchive) VectorVein.pkg
9152 INFO: Building PKG (CArchive) VectorVein.pkg completed successfully.
9154 INFO: Bootloader C:\Python311\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
9155 INFO: checking EXE
9155 INFO: Building EXE because EXE-00.toc is non existent
9156 INFO: Building EXE from EXE-00.toc
9156 INFO: Copying bootloader EXE to D:\vector-vein-dev\vector-vein\backend\build\main\VectorVein.exe.notanexecutable
9160 INFO: Copying icon to EXE
9160 INFO: Copying icons from ['D:\\vector-vein-dev\\vector-vein\\backend\\web/assets/favicon.ico']
9161 INFO: Writing RT_GROUP_ICON 0 resource with 90 bytes
9162 INFO: Writing RT_ICON 1 resource with 587 bytes
9162 INFO: Writing RT_ICON 2 resource with 67624 bytes
9162 INFO: Writing RT_ICON 3 resource with 16936 bytes
9163 INFO: Writing RT_ICON 4 resource with 9640 bytes
9163 INFO: Writing RT_ICON 5 resource with 4264 bytes
9163 INFO: Writing RT_ICON 6 resource with 1128 bytes
9167 INFO: Copying 0 resources to EXE
9168 INFO: Embedding manifest in EXE
9170 INFO: Updating manifest in D:\vector-vein-dev\vector-vein\backend\build\main\VectorVein.exe.notanexecutable
9172 INFO: Updating resource type 24 name 1 language 0
9174 INFO: Appending PKG archive to EXE
9176 INFO: Fixing EXE headers
9236 INFO: Building EXE from EXE-00.toc completed successfully.
9239 INFO: checking COLLECT
9239 INFO: Building COLLECT because COLLECT-00.toc is non existent
9241 INFO: Building COLLECT COLLECT-00.toc
9361 INFO: Building COLLECT COLLECT-00.toc completed successfully.
PS D:\vector-vein-dev\vector-vein\backend> dir


    目录: D:\vector-vein-dev\vector-vein\backend


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/6/17     11:20                .venv
d-----         2023/6/17     20:45                api
d-----         2023/6/17     23:45                build
d-----         2023/6/17     23:45                dist
d-----         2023/6/17     20:45                log
d-----         2023/6/17     20:45                models
d-----         2023/6/17     15:34                node_modules
d-----         2023/6/17     20:45                utilities
d-----         2023/6/17     21:02                web
d-----         2023/6/17     20:45                worker
-a----         2023/6/17     10:45           3255 .gitignore
-a----         2023/6/17     11:20             63 .pdm-python
-a----         2023/6/17     10:45           2635 build.py
-a----         2023/6/17     10:45           1293 debug.spec
-a----         2023/6/17     10:45           3160 main.py
-a----         2023/6/17     10:45           1297 main.spec
-a----         2023/6/17     15:47           7721 package-lock.json
-a----         2023/6/17     15:34             57 package.json
-a----         2023/6/17     15:47           1054 pyproject.toml
-a----         2023/6/17     10:45           1380 requirements-windows.txt


PS D:\vector-vein-dev\vector-vein\backend> cd dist
PS D:\vector-vein-dev\vector-vein\backend\dist> dir


    目录: D:\vector-vein-dev\vector-vein\backend\dist


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/6/17     23:45                vector-vein


PS D:\vector-vein-dev\vector-vein\backend\dist> cd vector*
PS D:\vector-vein-dev\vector-vein\backend\dist\vector-vein> dir


    目录: D:\vector-vein-dev\vector-vein\backend\dist\vector-vein


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/6/17     23:45                web
-a----         2023/6/17     23:45        1847603 base_library.zip
-a----          2023/6/7      6:02        3445016 libcrypto-1_1.dll
-a----          2023/6/7      6:02         704792 libssl-1_1.dll
-a----          2023/6/7      6:01        5762840 python311.dll
-a----          2023/6/7      6:01          30480 select.pyd
-a----          2023/6/7      6:01        1141016 unicodedata.pyd
-a----          2023/6/7      6:02         109392 VCRUNTIME140.dll
-a----         2023/6/17     23:45        2015004 VectorVein.exe
-a----         2023/6/17     23:45              5 version.txt
-a----          2023/6/7      6:01          84760 _bz2.pyd
-a----          2023/6/7      6:01         253200 _decimal.pyd
-a----          2023/6/7      6:01          65304 _hashlib.pyd
-a----          2023/6/7      6:01         158992 _lzma.pyd
-a----          2023/6/7      6:01          32528 _queue.pyd
-a----          2023/6/7      6:01          79640 _socket.pyd
-a----          2023/6/7      6:01         161040 _ssl.pyd
-a----          2023/6/7      6:01          25360 _uuid.pyd


PS D:\vector-vein-dev\vector-vein\backend\dist\vector-vein>

**Comment by AndersonBY** [comment]
`pdm run dev` 是正常的是么？

**Comment by jiangfangfangxm** [comment]
报错：
PS D:\vector-vein-dev\vector-vein\backend> pdm run dev
Traceback (most recent call last):
  File "D:\vector-vein-dev\vector-vein\backend\main.py", line 11, in <module>
    import webview
ModuleNotFoundError: No module named 'webview'

**Comment by AndersonBY** [comment]
那说明pywebview还是没装上啊，重新`pdm install`一下。装完了`pdm list`看看

**Comment by jiangfangfangxm** [comment]
pdm install ,报错：
  fatal: unable to access 'https://github.com/AndersonBY/clr-loader.git/': Failed to connect to github.com port 443 after 21062 ms: Couldn't connect to server

但我通过浏览器是可以访问的，是不是版本号不存在？如下截图所示：
![image](https://github.com/AndersonBY/vector-vein/assets/45526589/7a39b6e3-fa7b-4b34-9800-81e41d8d13b5)


下面是安装命令执行过程的输出信息：
PS D:\vector-vein-dev\vector-vein\backend> pdm install -v
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

unearth.vcs.git: Cloning https://github.com/AndersonBY/clr-loader.git (revision: c675dc8c08663d714c11705a23c84c2588a110e2) to C:\Users\JIANGF~1\AppData\Local\Temp\pdm-build-ax2rvhqp
  x Install clr-loader 0.2.6.dev2+gc675dc8 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\installers\synchronizers.py", line 275, in install_candidate
    self.manager.install(can)
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\models\candidates.py", line 375, in build
    self.obtain(allow_all=False)
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\models\candidates.py", line 427, in obtain
    self._unpack(validate_hashes=not allow_all)
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\models\candidates.py", line 441, in _unpack
    result = finder.download_and_unpack(self.link, build_dir, download_dir, hash_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\unearth\finder.py", line 391, in download_and_unpack
    file = unpack_link(
           ^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\unearth\preparer.py", line 283, in unpack_link
    backend.fetch(link, location)
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\unearth\vcs\base.py", line 145, in fetch
    return self.fetch_new(location, url, rev, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\unearth\vcs\git.py", line 50, in fetch_new
    self.run_command(
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\unearth\vcs\base.py", line 78, in run_command
    raise UnpackError(e.output) from None
unearth.errors.UnpackError: Cloning into 'C:\Users\JIANGF~1\AppData\Local\Temp\pdm-build-ax2rvhqp'...
fatal: unable to access 'https://github.com/AndersonBY/clr-loader.git/': Failed to connect to github.com port 443 after 21062 ms: Couldn't connect to server

Retry failed jobs
unearth.vcs.git: Cloning https://github.com/AndersonBY/clr-loader.git (revision: c675dc8c08663d714c11705a23c84c2588a110e2) to C:\Users\JIANGF~1\AppData\Local\Temp\pdm-build-p21bkf6j

**Comment by AndersonBY** [comment]
这个是你的终端没有走代理所以没能连接上 你得让终端也走代理，在终端里输入类似这样的指令来配置
```
$Env:http_proxy="http://127.0.0.1:7890";$Env:https_proxy="http://127.0.0.1:7890"
```

**Comment by s544838371** [comment]
> 这个是你的终端没有走代理所以没能连接上 你得让终端也走代理，在终端里输入类似这样的指令来配置
> 
> ```
> $Env:http_proxy="http://127.0.0.1:7890";$Env:https_proxy="http://127.0.0.1:7890"
> ```

这个确实是可行的

**Comment by jiangfangfangxm** [comment]
是否可以手动下载，然后本地安装呢？

**Comment by AndersonBY** [comment]
上面那个是配置代理，前提是你本地的代理是127.0.0.1:7890。我把github的仓库同步了一份到gitee，你可以把pyproject.toml里的
```
"clr-loader @ git+https://github.com/AndersonBY/clr-loader.git",
```
换成
```
"clr-loader @ git+https://gitee.com/AndersonBY/clr-loader.git",
```

**Comment by jiangfangfangxm** [comment]
仍然报错：
PS D:\vector-vein-dev\vector-vein\backend> pdm install
Lock file hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
  Lock successful
Changes are written to pdm.lock.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  x Install clr-loader 0.2.6.dev2+gc675dc8 failed
Retry failed jobs
  x Install clr-loader 0.2.6.dev2+gc675dc8 failed

ERRORS:
add clr-loader failed:
Traceback (most recent call last):
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\installers\synchronizers.py", line 275, in
install_candidate
    self.manager.install(can)
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\models\candidates.py", line 389, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\builders\wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pyproject_hooks\_impl.py", line 209, in
build_wheel
    return self._call_hook('build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pyproject_hooks\_impl.py", line 311, in
_call_hook
    self._subprocess_runner(
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\builders\base.py", line 260, in
subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiangfangfang\.local\pipx\venvs\pdm\Lib\site-packages\pdm\builders\base.py", line 107, in
log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
writing requirements to clr_loader.egg-info\requires.txt
writing top-level names to clr_loader.egg-info\top_level.txt
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.dll' found under directory 'clr_loader\ffi\dlls'
adding license file 'LICENSE'
writing manifest file 'clr_loader.egg-info\SOURCES.txt'
running build_dotnet
Running dotnet build...
dotnet build netfx_loader/ClrLoader.csproj --runtime win-x86 --configuration release --output
C:\Users\JIANGF~1\AppData\Local\Temp\pdm-build-3258dxsl\build\lib\clr_loader/ffi/dlls/x86
error: command 'dotnet' failed: None

See C:\Users\JIANGF~1\AppData\Local\Temp\pdm-install-9nsvj_h_.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback

下面是日志文件：
[pdm-install-9nsvj_h_.log](https://github.com/AndersonBY/vector-vein/files/11789042/pdm-install-9nsvj_h_.log)

**Comment by jiangfangfangxm** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/45526589/c15cf8d3-d8cd-4f12-9e7d-fb0ef0e516a2)

**Comment by AndersonBY** [comment]
按照pywebview文档的说法是requires > .NET 4.0

**Comment by s544838371** [comment]
> 按照pywebview文档的说法是requires > .NET 4.0

打包的时候我这边显示的是.net 7不知道是跟本地最高版本是否有关系

**Comment by AndersonBY** [comment]
我自己电脑上是.NET 7.0 没问题的

```
$ dotnet --info

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by jiangfangfangxm** [comment]
下载 .NET 7 后，运行 pdm install  已完成安装！
