### ISSUE TITLE
后端打开是空白，前端打开连不上服务器

### ISSUE THREAD

**Issue by hpstcgh** [AndersonBY/vector-vein#2]
我是新手，这是我第一个研究的项目， 不知道哪里错了，build也没有txt文件，所以这源码是不是不完整

**Comment by jchenibm** [comment]
我这边是前端build后能打开，但是workflow刷不出来，一直在转

**Comment by AndersonBY** [comment]
> 我是新手，这是我第一个研究的项目， 不知道哪里错了，build也没有txt文件，所以这源码是不是不完整

用的pyproject.toml，在backend目录下运行`pdm install`就可以了，会自动创建虚拟环境以及安装模块
pdm参考这里安装：[https://pdm.fming.dev/latest/](https://pdm.fming.dev/latest/)

另外需要注意pywebview目前在windows下还只支持到python3.8，这个得注意一下。

我这两天会把开发环境详细写一下。

**Comment by AndersonBY** [comment]
> 我这边是前端build后能打开，但是workflow刷不出来，一直在转

光开前端不行，因为数据库的创建和处理都得用到python后端，开发的时候目前都是打包好前端资源放到后端从后端启动来开发的。

**Comment by egg886** [comment]
我始终用不了pdm run build,它找不到dist目录，我运行pdm run dev之后，它是同时打开前后端吗，后端是空白的还是有界面的，前面单独单独能打开，只是连不上后端，pdm run dev同时打开两个，前端会出错，弹出一个web inspector窗口，显示body错误之类的，看不懂

**Comment by AndersonBY** [comment]
> 

有没有报错信息贴一下我看看

**Comment by egg886** [comment]
我直接python main.py运行了，这样不会报错，但是连不上前端打开之后连不上后端，是不是要你那边的服务器认证，但是要加参数才能连接成功

**Comment by AndersonBY** [comment]
> 我直接python main.py运行了，这样不会报错，但是连不上前端打开之后连不上后端，是不是要你那边的服务器认证，但是要加参数才能连接成功

那倒是不用，连我服务器这边只是获取一下版本更新信息，理论上不影响正常启动的。
前端控制台（Console）有没有什么报错信息

**Comment by egg886** [comment]
没有啊，不过我用的是ubuntu，我修改了一下你的库，它能工作，就是连不上后端，我想问的是，它后端是空白的吗，我看了那个你说的那个lang，我运行成功了，所以我不知道你这个后端打开是否是空白，还是有界面的

**Comment by AndersonBY** [comment]
> 没有啊，不过我用的是ubuntu，我修改了一下你的库，它能工作，就是连不上后端，我想问的是，它后端是空白的吗，我看了那个你说的那个lang，我运行成功了，所以我不知道你这个后端打开是否是空白，还是有界面的

`python main.py`运行之后是会打开一个界面的，像这样：
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/31d5ed6f-c356-4107-be37-42d8d5985ba3)

**Comment by egg886** [comment]
好的，我知道了，谢谢，我只有用npm run dev才会有这个界面，看来你这个后端是同时在程序里面内置了界面，我研究一下怎么在ubuntu工作

**Comment by AndersonBY** [comment]
> 好的，我知道了，谢谢，我只有用npm run dev才会有这个界面，看来你这个后端是同时在程序里面内置了界面，我研究一下怎么在ubuntu工作

我目前测试都是在Windows上的，非Windows的话可能还得看看pywebview的安装，依赖和Windows的不一样：[https://pywebview.flowrl.com/guide/installation.html#dependencies](https://pywebview.flowrl.com/guide/installation.html#dependencies)

**Comment by steelli** [comment]
目前是否支持macOS 呢？

**Comment by AndersonBY** [comment]
> 目前是否支持macOS 呢？

理论上是可以的，参考一下pywebview里关于Mac上安装的部分

**Comment by AndersonBY** [comment]
[https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip](https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip)

前端打开空白的问题，测试一下v0.0.5版本，感觉上是修复了空白的问题。
