### ISSUE TITLE
bug: 运行流程对应的 api 程序时，出错

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#22]
调用api 提供的程序如下：
import json
import time

import requests

api_key = "YOUR_API_KEY"
url = "https://vectorvein.com/api/v1/open-api/workflow/run"
headers = {
    "VECTORVEIN-API-KEY": api_key
}
payload = json.loads("""{
    "wid": "727be329d21b45d2bf2cf63861961c4b",
    "data": {
        "nodes": {
            "35ad4beb-1b5d-4ebc-8774-d13a27d34b5d": {
                "text": "6\n"
            }
        }
    }
}""")
response = requests.post(url, headers=headers, json=payload)
result = response.json()
print(response.status_code)
print(result)

if response.status_code != 200 or result["status"] != 200:
    print("Run workflow failed!")
    exit()

-------
在 juypter 中执行时报如下错误：

> JSONDecodeError                           Traceback (most recent call last)
[c:\Users\jiangfangfang\Downloads\apitest.ipynb](file:///C:/Users/jiangfangfang/Downloads/apitest.ipynb) Cell 2 in 1
      [8](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=7) url = "https://vectorvein.com/api/v1/open-api/workflow/run"
      [9](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=8) headers = {
     [10](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=9)     "VECTORVEIN-API-KEY": api_key
     [11](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=10) }
---> [12](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=11) payload = json.loads("""{
     [13](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=12)     "wid": "727be329d21b45d2bf2cf63861961c4b",
     [14](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=13)     "data": {
     [15](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=14)         "nodes": {
     [16](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=15)             "35ad4beb-1b5d-4ebc-8774-d13a27d34b5d": {
     [17](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=16)                 "text": "6\n"
     [18](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=17)             }
     [19](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=18)         }
     [20](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=19)     }
     [21](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=20) }""")
     [22](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=21) response = requests.post(url, headers=headers, json=payload)
     [23](vscode-notebook-cell:/c%3A/Users/jiangfangfang/Downloads/apitest.ipynb#W3sZmlsZQ%3D%3D?line=22) result = response.json()
File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
...
--> 353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
    355     raise JSONDecodeError("Expecting value", s, err.value) from None
JSONDecodeError: Invalid control character at: line 6 column 27 (char 162)

看来是 
  "text": "6\n"  --- 这个回车“\n" 导致的。
删除这个回车符，改为：
     "text": "6
运行报如下错：

> JSONDecodeError                           Traceback (most recent call last)
File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py:971](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/jiangfangfang/Downloads/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/requests/models.py:971), in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()
File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
...
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by AndersonBY** [comment]
YOUR_API_KEY 这里有没有替换为你自己的API_KEY？

**Comment by jiangfangfangxm** [comment]
由于是调用自己的chatGLM,因此，没有用到 openai-key. 另外看其报错，好象是在 执行  payload = json.loads 里报的错。

**Comment by AndersonBY** [comment]
不是，你上面给的程序是调用的我们SaaS平台的接口，和你自己的ChatGLM没关系

**Comment by jiangfangfangxm** [comment]
换了自己 open ai 的api_key 后仍然报错：
程序：
import json
import time
import requests


api_key = "-----------自己 open ai key---"
url = "https://vectorvein.com/api/v1/open-api/workflow/run"
headers = {
    "VECTORVEIN-API-KEY": api_key
}

payload_str = '''{
    "wid": "e1f5fefe36a648e6b495869edc066439",
    "data": {
        "nodes": {
            "257e48fa-8399-4b12-bf79-0aeb7f255864": {
                "text": "SELECT COUNT(*)  FROM cars "
            }
        }
    }
}'''
payload_str = payload_str.replace('\n', '').replace('    ', '')

print(payload_str)
payload = json.loads(payload_str)
print(payload)
response = requests.post(url, headers=headers, json=payload)
result = response.json()
print(response.status_code)
print(result)

if response.status_code != 200 or result["status"] != 200:
    print("Run workflow failed!")
    exit()

----
输出如下：
{"wid": "e1f5fefe36a648e6b495869edc066439","data": {"nodes": {"257e48fa-8399-4b12-bf79-0aeb7f255864": {"text": "SELECT COUNT(*)  FROM cars "}}}}
{'wid': 'e1f5fefe36a648e6b495869edc066439', 'data': {'nodes': {'257e48fa-8399-4b12-bf79-0aeb7f255864': {'text': 'SELECT COUNT(*)  FROM cars '}}}}

---
从报错信息看，应该是：result = response.json() ，这句报错。
具体出错信息如下：
----------------------------------
JSONDecodeError                           Traceback (most recent call last)
File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py:971](https://file+.vscode-resource.vscode-cdn.net/d%3A/vector-vein-dev/vector-vein-main/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/requests/models.py:971), in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File [C:\Program](file:///C:/Program) Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
...
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by AndersonBY** [comment]
不是，API_KEY是我们向量脉络网站上的API_KEY
[这里获取](https://vectorvein.com/account/developer-api)

**Comment by jiangfangfangxm** [comment]
可以了，多谢！。不好意思，没有理解到这个差别。不过这个出错信息，也比较费解。
