### ISSUE TITLE
功能建议：增加一个输出构件：以Mermaid语言描述的流程图

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#23]
为了支持 流程图的生成，建议增加一个类似于 生成 思维导图的构件。
流程描述语言是 ：Mermaid.

下面是我问GPT的回答：

<img width="378" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/45526589/436a3778-98c3-426e-b064-b4d941dd0857">

**Comment by AndersonBY** [comment]
现在添加了，不过是用前端渲染的，不是用后端渲染的。
