### ISSUE TITLE
功能建议：python函数的界面输出作为构件的输出

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#24]
现在可以调用python程序，但只能接受python的返回值。不能有print语句，不能有画图语句。
由于想利用生成的python进行数据分析，因此，会希望python程序基于给定的数据画出图表，如柱状图，折线图。
因此希望能够提供 把 python函数的 界面输出，作为构件的输出的功能。

**Comment by AndersonBY** [comment]
整合Jupyter不太可能，这个太重了。接下来会尝试把echarts结合进来，到时候只需要用Python的pyecharts来生成echarts的配置传到前端就可以渲染出图表了。

**Comment by jiangfangfangxm** [comment]
我想到一个方法，在python程序中，就要求把 结果 输出到一个文件当中。然后返回这个文件。
想问一下，若python函数返回了一个文件，后续使用什么控制，能够展示这个文件的内容？或者图片的内容？

下面是 GPT给我的建议：
![image](https://github.com/AndersonBY/vector-vein/assets/45526589/91fcb2ef-3ac8-4b2e-a247-b507de0044e1)

**Comment by AndersonBY** [comment]
正在用pyecharts做图表，echarts的图表效果比较好

**Comment by AndersonBY** [comment]
已添加Echarts输出节点，效果如图
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/827fbe75-8dab-4455-b8e1-e28569a0eb25)

**Comment by jiangfangfangxm** [comment]
如何实现输出图表呢？ 调用哪个构件？还是python程序要如何写？

**Comment by AndersonBY** [comment]
> 如何实现输出图表呢？ 调用哪个构件？还是python程序要如何写？

参考这个模板：[📊自然语言描述生成数据图表](https://vectorvein.com/workspace/workflow/template/71910707192e4cc296d9457e163f0139)

**Comment by jiangfangfangxm** [comment]
可以了，多谢！
