### ISSUE TITLE
功能建议：自己分享的模板，可以删除

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#25]
发现自己分享的模板已过时，想更新一版，但旧的无法删除，且分享过后，就与原有模板分开了。因此想要更新，就需要再去修改它。
为了省事，就新发布一个，导致有些重复了。且容易造成困惑。
建议：
1、可以删除分享的模板；
2、或者与自己那个原始模板保持关连，联动。

**Comment by AndersonBY** [comment]
现在可以删除模板了，暂时没有加关联关系。
