### ISSUE TITLE
Bug: 在修改工作流基本信息时，在进行标签选择时，下拉的标签有重复

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#26]
<img width="613" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/45526589/8c94b7d0-48e4-4f17-bd43-fb481e3f1302">

**Comment by AndersonBY** [comment]
因为是直接输入已存在的标签而不是选择列表里的元素，所以后端重复创建了。已经修复
