### ISSUE TITLE
建议：支持chatglm2-6b 的调用

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#27]
据说，chatglm2-6B 比chatglm-6B有较大提升。为了便于测试比较其功能，是否可以让 chatglm 构件中，可以选择 chatglm2-6B.

**Comment by AndersonBY** [comment]
都是调用同样的API，不需要我这边改代码的。

**Comment by jiangfangfangxm** [comment]
我是指你提供的“vector-vein 平台”上的构件中能够调用chatglm2-6b , 而不是程序提供支持。

**Comment by AndersonBY** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/7f7d8599-8104-42ae-a4de-844920b1a6d8)
zhipuguanfang
智谱官方目前没给chatglm2-6b的接口调用，不确定lite是不是chatglm2

**Comment by jiangfangfangxm** [comment]
OK. 我以为chatGLM-6b是你自己本地部署的。如果是调用官方的，那就等等看了。
