### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by s544838371** [AndersonBY/vector-vein#28]
大佬好，我看工作流模板没有与你的在线版上的同步，是否以后会同步？另外浏览器插件是否能够支持本地的开源版本？

**Comment by AndersonBY** [comment]
线上的工作流节点和本地的有些是有区别的，所以还没同步，我今天晚点同步一下。浏览器插件目前不支持本地版本，因为是通过API方式调用的，本地的这个版本没有API接口。

**Comment by s544838371** [comment]
> 线上的工作流节点和本地的有些是有区别的，所以还没同步，我今天晚点同步一下。浏览器插件目前不支持本地版本，因为是通过API方式调用的，本地的这个版本没有API接口。

@AndersonBY 
大佬，后续是否考虑支持通过设置IP+端口+API的方式？
然后我看微信群里大家都没说话，是咋回事emmm，昨天刚刚加了群

**Comment by AndersonBY** [comment]
PC端用的pywebview，如何暴露接口出来我还得研究一下。
欢迎在群里聊，我本身是不太发言的那种，欢迎来唠唠

**Comment by s544838371** [comment]
> PC端用的pywebview，如何暴露接口出来我还得研究一下。 欢迎在群里聊，我本身是不太发言的那种，欢迎来唠唠

了解
