### ISSUE TITLE
建议：关系数据表的操作

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#29]
有时，需要基于结构化数据进行LLM 模型前的 输入准备，是否可以 在你发布的平台上，增加 类似向量数据库一样的几个构件：
1、增加数据
2、修改数据
3、删除数据
4、查找数据
当然之前，需要先建一个 数据表。

或者就 只提供一个SQL语句的构件来实现上述操作

**Comment by AndersonBY** [comment]
这个主要的麻烦点在于数据安全的问题，需要考虑避免影响到数据库的整体安全，我得考虑一下如何平衡。

**Comment by AndersonBY** [comment]
最新的 v0.1.0 版本已经实现。
