### ISSUE TITLE
pdm run dev 页面空白

### ISSUE THREAD

**Issue by SmileSmith** [AndersonBY/vector-vein#3]
控制台报错信息如下，应该是返回的js文件 mimeType指定错误

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

![image](https://github.com/AndersonBY/vector-vein/assets/17798955/b8635db1-ae77-4804-895e-6759af287f51)

![image](https://github.com/AndersonBY/vector-vein/assets/17798955/90e84f5c-2370-40b9-a558-af0813d063f2)

**Comment by AndersonBY** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/fba3e4b8-5726-431c-bce4-55fd49136400)
我这边有内容，你看看这个js的响应里面有没有内容？
另外看看是不是webview的问题[https://developer.microsoft.com/en-us/microsoft-edge/webview2/](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)
试试更新webview会不会有用

**Comment by AndersonBY** [comment]
[https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip](https://github.com/AndersonBY/vector-vein/releases/download/v0.0.5/vector-vein-windows.zip)

测试一下v0.0.5版本，感觉上是修复了空白的这个问题。
