### ISSUE TITLE
建议：工具--文本搜索 构件的输出字数控制 

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#30]
问题；在通过搜索获取相关信息，合并成一个本文，然后要输出给 chatGLM 时，有时会由于输出的数据量过大，导致 token超出了，引起错误。
建议：在 文本搜索 构件输出时，是否可能增加一个“字数”控制。

对于 文本爬虫 是不是也有这样需求，控制输出的最大字数。 

当然，也许只需要 在 chatGLM输入时，截取自己能够处理的最大token数量，就能解决这个问题。

**Comment by AndersonBY** [comment]
增加了一个 **文本截断** 节点，可以参考：[文本截断](https://vectorvein.com/help/docs/text-processing#h2-20)。
