### ISSUE TITLE
建议：增加一个支持 function Calling的 OpenAI结点

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#32]
为了使用 OpenAI 提供的 function calling 功能，在调用时，可以有两个参数：functions, function_call.
也许将来其它的大模型也会提供这样的接口功能。
只是这个功能，对于会编程者会作用大一些。
样例：https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb

**Comment by AndersonBY** [comment]
过两天研究一下怎么结合比较好，这几天在开发向量脉络的微信小程序

**Comment by s544838371** [comment]
> 为了使用 OpenAI 提供的 function calling 功能，在调用时，可以有两个参数：functions, function_call. 也许将来其它的大模型也会提供这样的接口功能。 只是这个功能，对于会编程者会作用大一些。 样例：[openai/openai-cookbook@`main`/examples/How_to_call_functions_with_chat_models.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb?rgh-link-date=2023-07-29T03%3A47%3A12Z)

Function Call： Chat 应用的插件基石与交互技术的变革黎明？
看过一篇文章，通过Function Call可以开发插件？
https://sspai.com/post/81986

**Comment by AndersonBY** [comment]
[v0.0.26](https://github.com/AndersonBY/vector-vein/releases/tag/v0.0.26) 现在已经支持Function Call了。
[vectorvein.com](https://vectorvein.com) 在线版这两天会同步更新上。

**Comment by s544838371** [comment]
@jiangfangfangxm 快来试试
话说怎么用Function Call？教一教

**Comment by s544838371** [comment]
> [v0.0.26](https://github.com/AndersonBY/vector-vein/releases/tag/v0.0.26) 现在已经支持Function Call了。 [vectorvein.com](https://vectorvein.com) 在线版这两天会同步更新上。

666
