### ISSUE TITLE
建议：提供一个“工作流调用"结点

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#34]
每个配置好的工作流实际上就是一个小的tool. 就如你的：优化prompt。 
为了提高效率，或实现更复杂的工作流，需要利用各种配置好的工作流，把这些工作流象搭积木一样，构造更加复杂或抽象的工作流。

当前可以通过写python函数结点来实现 api的调用，但对于一般的人员，有些木槛。
因此建议：
     提供一个 api结点，只需要把地址填进去，把输入、输出连接定义好，就可以了。

难点：不知道输入、输出的参数个数。 这个需要自己去配置了。

**Comment by AndersonBY** [comment]
说得非常对，我之前就有打算这么做了，这个实现出来之后可以实现更多子任务拆分，工作流复用，还是挺需要的。

**Comment by AndersonBY** [comment]
在网页端先实现了，开源版的近期开发一下：[工作流调用](https://vectorvein.com/help/docs/tools#h2-12)

**Comment by AndersonBY** [comment]
已实现：[v0.0.24](https://github.com/AndersonBY/vector-vein/releases/tag/v0.0.24)
