### ISSUE TITLE
如何在linux上使用吗, 请问支持linux吗

### ISSUE THREAD

**Issue by wayne-data** [AndersonBY/vector-vein#36]

**Comment by AndersonBY** [comment]
没在 Linux 上测试过，关键是看 pywebview，你可以试一下。
[https://pywebview.flowrl.com/guide/installation.html#dependencies](https://pywebview.flowrl.com/guide/installation.html#dependencies)

**Comment by wayne-data** [comment]
> 没在 Linux 上测试过，关键是看 pywebview，你可以试一下。 https://pywebview.flowrl.com/guide/installation.html#dependencies

我太笨了 我搞了两个小时 没搞出来
但好像快成功了 最后弄到这里 可以帮忙看看吗?? 
![image](https://github.com/AndersonBY/vector-vein/assets/104449006/703663b3-10f8-4cb2-a390-281918814401)

![image](https://github.com/AndersonBY/vector-vein/assets/104449006/4dbe27d4-d7d8-441d-80b5-27a42df8ddb6)

**Comment by wayne-data** [comment]
我这边是centos  哎 干脆用docker算了

**Comment by AndersonBY** [comment]
纯终端啊，这启动了也没法用吧？

**Comment by wayne-data** [comment]
> 纯终端啊，这启动了也没法用吧？

开源版 的 不能部署linux然后前端nginx 转发网址?   webview之前没接触过?

**Comment by AndersonBY** [comment]
开源版的是本地跑的PC端软件，用的pywebview框架，不是SaaS

**Comment by seetimee** [comment]
请问后续会支持linux吗

**Comment by AndersonBY** [comment]
> 请问后续会支持linux吗

如果是有图形界面的 Linux 理论是是可以的
