### ISSUE TITLE
功能建议：支持本地化部署的LLM模型

### ISSUE THREAD

**Issue by libhot** [AndersonBY/vector-vein#4]
例如国产的ChatGLM等模型，而不能仅支持OpenAI的接口

**Comment by AndersonBY** [comment]
是TODO里的，不过有一点工程量，希望有帮忙的朋友

**Comment by libhot** [comment]
可以参考一下wenda、langchain-ChatGLM ，这些都是调用本地LLM的

**Comment by jiangfangfangxm** [comment]
目前，构件的名称仍然显示为: OpenAI ,不知在什么地方修改。

<img width="214" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/45526589/b5223355-14f5-4dff-ba69-3be1a60be3be">

在构件树中，显示的为： components.node.. 而非 chatGLM ,不知什么地方修改。
<img width="99" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/45526589/848bca8f-d059-43b3-840d-def4e6335512">

**Comment by AndersonBY** [comment]
> 

名称、翻译之类的是在前端的locales里修改的，我待会测试一下，OK的话增加一个ChatGLM-6B的节点试试

**Comment by AndersonBY** [comment]
已经添加ChatGLM节点，通过API的方式调用ChatGLMGLM-6B。

调用的方式参考 [https://github.com/THUDM/ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B) 里的api.py
