### ISSUE TITLE
建议：实现Agent的构件

### ISSUE THREAD

**Issue by jiangfangfangxm** [AndersonBY/vector-vein#40]
我理解，当前工作流类似于langchain中的 chain对象，可以完成一些 目标具体的操作性任务。未来更广泛的应用领域，可能是AI agent. 不知有没有可能在这里 提供 agent 及 agent executor的 控制或对象。
类似这个开源项目实现的架构：
https://github.com/filip-michalsky/SalesGPT

我也理解，当前的应用框架是针对工作流的，可能不太容易实现 “多次交互式”的能力，也许也没有必要去集成这个能力。
一个可能的解决方案 在别的框架中，调用这里定制的工作流即可。 仅供参考。

**Comment by AndersonBY** [comment]
AI Agent 确实是我最近在思考的结合方向，工作流与 Agent 有相似的地方，不过侧重点会不同，这个我最近打算写个文章分析一下。

工作流更侧重在过程可控、流程可重复、成本可控制等方向，发散性没有 Agent 那么高，或者说以人的思考和规划代替了 Agent 的一部分思考和规划以达到生产级可用的效果。

多次交互的聊天型能力这个我觉得也是有可能集成的，一种简单的思路就是用户的每次聊天输入都会触发一次工作流，而聊天内容本身会被作为一次新的内容输入到新一次工作流运行当中。

**Comment by AndersonBY** [comment]
目前最新的开源版已经实现 Agent 功能，与线上版相同，而且支持语音输入输出。
