### ISSUE TITLE
官方示例的Agent何时能开源呢

### ISSUE THREAD

**Issue by GlitterMessi** [AndersonBY/vector-vein#44]
<img width="1066" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/144041174/498df529-fe2a-46ac-829a-c34a5a9072e8">

**Comment by AndersonBY** [comment]
这个肯定会开源，不过工作量要大一些，得一点点来

**Comment by GlitterMessi** [comment]
> 这个肯定会开源，不过工作量要大一些，得一点点来

了解，现在开源版也只支持桌面端运行不支持浏览器直接运行是吗

**Comment by AndersonBY** [comment]
对，PC端的，底层用的webview

**Comment by AndersonBY** [comment]
目前最新的开源版已经实现 Agent 功能，与线上版相同，而且支持语音输入输出。
