### ISSUE TITLE
关于连线的svg 连接线圆点！

### ISSUE THREAD

**Issue by Rookie-zrx** [AndersonBY/vector-vein#46]
我看官网也没说到可配置的svg 连接线圆点，这个项目中却用到了，而且不是自定组件的，我想改成箭头的，但是在找不出来！
![image](https://github.com/AndersonBY/vector-vein/assets/54833166/22f90ade-b969-4d4a-bd12-ff431cd9b8af)

**Comment by Rookie-zrx** [comment]
> 你是在说 vue-flow 的配置？

是的

**Comment by Rookie-zrx** [comment]
> 端点 Handler 的圆圈是自己手动改 style 调的。

是图中的 svg 连接线哦，连接线前后有透明色的圆点的

**Comment by AndersonBY** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/35dac830-7f2f-4b8c-b5c0-83b7df1ab132)

VueFlow 官网示例就有配置啊 [https://vueflow.dev/examples/](https://vueflow.dev/examples/)

**Comment by Rookie-zrx** [comment]
> ![image](https://private-user-images.githubusercontent.com/3096131/320796613-35dac830-7f2f-4b8c-b5c0-83b7df1ab132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTUyMjEsIm5iZiI6MTcxMjY1NDkyMSwicGF0aCI6Ii8zMDk2MTMxLzMyMDc5NjYxMy0zNWRhYzgzMC03ZjJmLTRiOGMtYjVjMC04M2I3ZGYxYWIxMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDkyODQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRjNWJhM2NkNTc4ZWM0NzEzOWY4YmU0NTUzNGE3N2I5MDYxYmNiZDAwYjJiOGIzNDBmYmVkNmU5ZjMzNmM0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.taDv5MulVb0EIE64XWEYeMm69LLna9_x8xtXwEJ9eVE)
> 
> VueFlow 官网示例就有配置啊 https://vueflow.dev/examples/

很奇怪，我看官网配置箭头是用了markerEnd：MarkerType.ArrowClosed，但是我用在这个项目上还是显示那两个透明的圆点
![image](https://github.com/AndersonBY/vector-vein/assets/54833166/8fa98d5f-a679-4d36-b13c-dfc59d710ad0)

**Comment by AndersonBY** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/3096131/27c8aed1-b5b5-4c79-83fa-f61bc6bfaff2)

![image](https://github.com/AndersonBY/vector-vein/assets/3096131/9f3c83c6-60d9-4069-8875-51d439038cb0)


我手动给连线加 markerEnd 都可以实现箭头效果。

**Comment by Rookie-zrx** [comment]
> ![image](https://private-user-images.githubusercontent.com/3096131/320813090-27c8aed1-b5b5-4c79-83fa-f61bc6bfaff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTExMzQsIm5iZiI6MTcxMjcxMDgzNCwicGF0aCI6Ii8zMDk2MTMxLzMyMDgxMzA5MC0yN2M4YWVkMS1iNWI1LTRjNzktODNmYS1mNjFiYzZiZmFmZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDEwMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA2MDEzNmQ2MGFhN2E2ZmM4MDBlMDM0OTZlODk5N2NhNjY4NGM4MDcwZjFkOTMzOWU3Yzk2MDU0OTVjMDI2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aq0pz8X8xp5T_d3YkibuN_zKe549ZA5jopdamvmWYi0)
> 
> ![image](https://private-user-images.githubusercontent.com/3096131/320813210-9f3c83c6-60d9-4069-8875-51d439038cb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTExMzQsIm5iZiI6MTcxMjcxMDgzNCwicGF0aCI6Ii8zMDk2MTMxLzMyMDgxMzIxMC05ZjNjODNjNi02MGQ5LTQwNjktODg3NS01MWQ0MzkwMzhjYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDEwMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFlZWVhOGRlYmFmMmU2NGYxMTI2OTkxYWZlODJlMTcyMzg0YjQwZGI0MTIxMmYxMzkyYzFkNmJlMDliM2YzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.77Au6uCiDbgf2eduScE4jlwB7RQrq548KCPakytNJIA)
> 
> 我手动给连线加 markerEnd 都可以实现箭头效果。

可能是版本不一致，我这里手动改他的代码都是一直存在的，
![image](https://github.com/AndersonBY/vector-vein/assets/54833166/cc12f3ec-3f43-4997-8a70-43af5060194a)
