### ISSUE TITLE
0.1x 版本无法保存工作流

### ISSUE THREAD

**Issue by xuze1993** [AndersonBY/vector-vein#47]
0.31版本正常的，到0.1x版本无法保存工作流，会卡住。

**Comment by AndersonBY** [comment]
你看看软件目录下的log里是什么提示？

**Comment by xuze1993** [comment]
> 你看看软件目录下的log里是什么提示？

好像没有什么error，界面是一直卡着
![图片](https://github.com/AndersonBY/vector-vein/assets/35798540/6e1cf7a3-5879-4b49-a89b-58a9c30dd79c)

![图片](https://github.com/AndersonBY/vector-vein/assets/35798540/2595e6a9-6431-4272-881a-7636c8d847c4)

**Comment by AndersonBY** [comment]
https://github.com/AndersonBY/vector-vein/releases/download/v0.1.1/vector-vein-windows-v0.1.1-debug.zip

加了一个 debug 版本，你用这个打开试试，然后保存之前在页面点右键->检查，看看控制台点保存是时候有什么报错信息

**Comment by xuze1993** [comment]
> https://github.com/AndersonBY/vector-vein/releases/download/v0.1.1/vector-vein-windows-v0.1.1-debug.zip
> 
> 加了一个 debug 版本，你用这个打开试试，然后保存之前在页面点右键->检查，看看控制台点保存是时候有什么报错信息

![图片](https://github.com/AndersonBY/vector-vein/assets/35798540/8c79a465-dd9e-422c-b752-07c70dc99cb7)

**Comment by AndersonBY** [comment]
查了一下是因为你把触发器连线到其它节点了，这个节点本身不需要跟别的节点连起来的，更新了一个版本修复了这个问题。
https://github.com/AndersonBY/vector-vein/releases/tag/v0.1.2

**Comment by xuze1993** [comment]
> 查了一下是因为你把触发器连线到其它节点了，这个节点本身不需要跟别的节点连起来的，更新了一个版本修复了这个问题。 https://github.com/AndersonBY/vector-vein/releases/tag/v0.1.2

原来如此。还是从0.11往下开发吧，0.12试了下前端会报个孤立节点的错，但可以正常保存

**Comment by AndersonBY** [comment]
不是报错，因为你画布上除了触发器只有一个节点。

**Comment by AndersonBY** [comment]
测了一下确实有孤立结点的问题，我这边更新了一个版本：https://github.com/AndersonBY/vector-vein/releases/download/v0.1.3/vector-vein-windows-v0.1.3.zip
