### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by DevX480** [AndersonBY/vector-vein#58]
Please add a dark mode under settings. Love the program but the white background hurts my eyes after a while. Thanks.

**Comment by AndersonBY** [comment]
Sure, working on it now.

**Comment by AndersonBY** [comment]
Done. https://github.com/AndersonBY/vector-vein/releases/tag/v0.2.6

**Comment by DevX480** [comment]
Wow, that's amazing. I've never had an actual dev message me and get a
change out so fast. I feel honored 🙂.
Your program is very interesting, keep up the good work.

**Comment by AndersonBY** [comment]
Glad you like this program!
