### ISSUE TITLE
下载后打开VectorVein软件是什么意思

### ISSUE THREAD

**Issue by haorunze** [AndersonBY/vector-vein#6]
请问怎么打开软件？

**Comment by AndersonBY** [comment]
[https://github.com/AndersonBY/vector-vein/releases](https://github.com/AndersonBY/vector-vein/releases)
下载压缩包本地解压缩

**Comment by haorunze** [comment]
![下载问题](https://github.com/AndersonBY/vector-vein/assets/33285301/0bc99865-03d5-497c-8429-75490e96a35b)
下载时总是遇到这个问题，可能是墙的原因。试了网上各种方法还是不行。
作者大佬能不能做一个百度网盘之类的分享，很想试一下您的这个项目，谢谢！

**Comment by AndersonBY** [comment]
[https://pan.baidu.com/s/1cuVI_fOtsNAT4jm6vtUE7A?pwd=vein](https://pan.baidu.com/s/1cuVI_fOtsNAT4jm6vtUE7A?pwd=vein)
