### ISSUE TITLE
window下无法启动成功

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#60]
Traceback (most recent call last):
  File "main.py", line 210, in <module>
  File "main.py", line 206, in main
  File "webview\__init__.py", line 166, in start
  File "webview\guilib.py", line 134, in initialize
  File "webview\guilib.py", line 83, in try_import
  File "webview\guilib.py", line 72, in import_winforms
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from D:\vector-vein\_internal\pythonnet\runtime\Python.Runtime.dll

本地的python 环境为3.11.9

**Comment by AndersonBY** [comment]
不打包的时候能启动么

**Comment by suepradun** [comment]
使用开发模式可以正常启动而且使用本地打包运行也是ok的。

**Comment by AndersonBY** [comment]
> 使用开发模式可以正常启动而且使用本地打包运行也是ok的。

开发模式能启动打包后也正常运行的话，那你上面的报错是在啥情况下出现的？

**Comment by suepradun** [comment]
使用0.2.7的release直接启动出现的。

**Comment by AndersonBY** [comment]
发了一个新版：[v0.2.8](https://github.com/AndersonBY/vector-vein/releases/download/v0.2.8/vector-vein-windows-v0.2.8.zip)，看看还有没有报错。

**Comment by suepradun** [comment]
还是报错
![image](https://github.com/user-attachments/assets/2f0ed022-dc33-420f-91d7-2f2779fcba0b)

**Comment by AndersonBY** [comment]
看起来 和这两个 issue 都一样的：
https://github.com/r0x0r/pywebview/issues/1215
https://github.com/AndersonBY/vector-vein/issues/41

你看看在你的 PowerShell 运行下面指令，看看你的 .net 是多少的版本
```
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full" /v version
```

**Comment by suepradun** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full
    version    REG_SZ    4.8.09032

**Comment by AndersonBY** [comment]
实在解决不了，还是和 pythonnet 和 .net 有关，太难搞了

**Comment by suepradun** [comment]
对比了正常启动的机器， 里面对应的python版本与.net framework版本都是一样的。
应该是其他系统环境因素引起的。

**Comment by kundeng** [comment]
having the same problem.

**Comment by kundeng** [comment]
Hey I finally found out the issue, your build is fine:  here is what you can put in your readme, after they download the zip, they need to "unblock" the zip before unzipping it. See the pic.   

**
<img width="319" alt="image" src="https://github.com/user-attachments/assets/68b9ceb4-1092-471d-be31-8d2452442c09">
**

**Comment by kundeng** [comment]
> 还是报错 ![image](https://private-user-images.githubusercontent.com/59818764/364267862-2f0ed022-dc33-420f-91d7-2f2779fcba0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTIwMDcsIm5iZiI6MTcyNjYxMTcwNywicGF0aCI6Ii81OTgxODc2NC8zNjQyNjc4NjItMmYwZWQwMjItZGMzMy00MjBmLTkxZDctMmYyNzc5ZmNiYTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDIyMjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGFjOTI0MGY2ODk2YzhjMWJjYTAxMGY1YjBiZjMyZGNhM2M1ZDNkNTIzZjFlZWI2NTJhMWIxZjA2YjUxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONBZ0V_CaDbfZsrIgbAxiLCvecDCUPX4Qo-Lhbb2uZI)

see above.

**Comment by BlueDarkUP** [comment]
孩子们，你们无法想象这是为什么，原因就是windows发觉这个dll文件来源于另外一个计算机，安全起见不让你用，所以事实上只需要右键dll文件属性解除锁定就行了

**Comment by BlueDarkUP** [comment]
这个文件的位置就在
.\vector-vein\_internal\pythonnet\runtime

**Comment by suepradun** [comment]
> 孩子们，你们无法想象这是为什么，原因就是windows发觉这个dll文件来源于另外一个计算机，安全起见不让你用，所以事实上只需要右键dll文件属性解除锁定就行了

但同样的文件有些机器可以，有些不行，是因为window设置么？是什么设置？

**Comment by AndersonBY** [comment]
> 孩子们，你们无法想象这是为什么，原因就是windows发觉这个dll文件来源于另外一个计算机，安全起见不让你用，所以事实上只需要右键dll文件属性解除锁定就行了

我说怎么老是复现不了，必须得换个电脑，估计还有安全策略不同也会有影响吧

**Comment by BlueDarkUP** [comment]
> > 还是报错![图像](https://private-user-images.githubusercontent.com/59818764/364267862-2f0ed022-dc33-420f-91d7-2f2779fcba0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MTIwMDcsIm5iZiI6MTcyNjYxMTcwNywicGF0aCI6Ii81OTgxODc2NC8zNjQyNjc4NjItMmYwZWQwMjItZGMzMy00MjBmLTkxZDctMmYyNzc5ZmNiYTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDIyMjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGFjOTI0MGY2ODk2YzhjMWJjYTAxMGY1YjBiZjMyZGNhM2M1ZDNkNTIzZjFlZWI2NTJhMWIxZjA2YjUxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONBZ0V_CaDbfZsrIgbAxiLCvecDCUPX4Qo-Lhbb2uZI)
> 
> 见上文。

这个图象打不开，我猜是关于沙盒化的，你可以把.net版本换成 .NET Framework 3.5及之前的

**Comment by BlueDarkUP** [comment]
参考https://learn.microsoft.com/zh-cn/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element

**Comment by BlueDarkUP** [comment]
> > 孩子们，你们无法想象这是为什么，原因就是windows发觉这个dll文件来源于另外一个计算机，安全起见不让你用，所以事实上只需要右键dll文件属性解除锁定就行了
> 
> 但同样的文件有些机器可以，有些不行，是因为window设置么？是什么设置？

根据我的报错猜测应当是<loadFromRemoteSources>开关
如果你用linux的话同样运行一些软件会让你加上 --no--sandbox，都是同样的问题

**Comment by BlueDarkUP** [comment]
捣鼓到现在，每次解决一个问题都会有别的报错，原因就是安装的项目使用了exe自动下载的库，而这些库都被标记成来自于其他的设备，所以整个下载下来的所有文件都会被锁定，而且我暂时没有找到方法来解除锁定所有的文件，所以我认为解决方法就是只提供一个bat脚本，用户电脑上本身就有符合条件的python，所有库和虚拟环境在用户的电脑上下载创建，我觉得可以参考一下GPT学术优化的一键安装脚本，除此之外没有任何方法信任这个文件，即使添加到白名单或者关闭实时保护，因为标记在下载的一瞬间就完成了

**Comment by BlueDarkUP** [comment]
问题我解决了

**Comment by AndersonBY** [comment]
> 捣鼓到现在，每次解决一个问题都会有别的报错，原因就是安装的项目使用了exe自动下载的库，而这些库都被标记成来自于其他的设备，所以整个下载下来的所有文件都会被锁定，而且我暂时没有找到方法来解除锁定所有的文件，所以我认为解决方法就是只提供一个bat脚本，用户电脑上本身就有符合条件的python，所有库和虚拟环境在用户的电脑上下载创建，我觉得可以参考一下GPT学术优化的一键安装脚本，除此之外没有任何方法信任这个文件，即使添加到白名单或者关闭实时保护，因为标记在下载的一瞬间就完成了。即使我在组策略编辑器中的“文件附件中不保留区域信息”选择了启用，但我重新下载的ZIP文件中的文件还是有解除锁定选项，所以我怀疑源文件本身就带有来自其他计算机的选项

可能会考虑用安装包的方式提供给用户

**Comment by BlueDarkUP** [comment]
> Owner

不必了，看我最新的留言。。。。
我们都想得太多了

**Comment by AndersonBY** [comment]
> > Owner
> 
> 不必了，看我最新的留言。。。。 我们都想得太多了

我在 README 里加一下
