### ISSUE TITLE
建议增加对硅基流动的支持

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#62]
一套接口能方便调用各种模型

**Comment by AndersonBY** [comment]
![image](https://github.com/user-attachments/assets/1d1fff8e-2f28-42c0-941f-5a75aa93c915)

你可以在这里自行增加提供商和模型列表，硅基流动或者别的都可以。

**Comment by suepradun** [comment]
模型系列能加载出来，但是模型列表加载不出来。
![image](https://github.com/user-attachments/assets/40497de8-0104-4377-b2b0-a45a810a0300)
![image](https://github.com/user-attachments/assets/3b6e9e75-5456-4eb8-ac82-8ce33e281b08)

**Comment by AndersonBY** [comment]
![image](https://github.com/user-attachments/assets/0d91ac09-c585-4407-82ae-d191e38be0ae)

不会呀，正常的，你是不是没点开
