### ISSUE TITLE
HTML 组件异常

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#63]
输入html代码 后显示404。
看起来这个组件是先把html存起文件，然后在显示这个文件，现在找不到文件。
已经有了保存文件的组件，这样做是不是有点多余。

![image](https://github.com/user-attachments/assets/d78b103b-fc0b-4533-8994-1d94088f2c58)

**Comment by AndersonBY** [comment]
你在你的设置里 其他 -> 输出文件夹 看看路径配置，可以重新设置一个输出文件夹。这个组件是为了直接呈现 HTML 的，作用不太一样。

**Comment by suepradun** [comment]
我重新设置了输出文件夹，但是无论我怎么选，它都只是输出了盘符而不是对应的路径。这就导致了后续运行出错。
，如我选了D盘下的一个目录，只显示 "D".
![image](https://github.com/user-attachments/assets/0662d531-ab43-48d4-9a36-af0abb463c38)

**Comment by AndersonBY** [comment]
所有路径选择都是这样吗还是只有这个？我晚点查一下。

**Comment by suepradun** [comment]
不敢试了，试了就改不回来了。 涉及到的流程都会跑不起来。

**Comment by AndersonBY** [comment]
刚发了 v0.2.10 版本，应该修复完了。不过注意配置信息结构有更新，建议提前备份数据库再测试新版。
