### ISSUE TITLE
In what way is this better than langflow and many other similar apps like rivet.ai or flowwise etc etc? 

### ISSUE THREAD

**Issue by kundeng** [AndersonBY/vector-vein#64]
Thanks!

**Comment by AndersonBY** [comment]
We focus on workflow usage itself not by adding it as an ability to chatbot.

**Comment by kundeng** [comment]
Hey thanks. It seems so! I got here from looking for a HARPA.ai alternative. HARPA.ai is a browser-only extension, at least for now, which allows users to author workflows in GUI or directly in YAML.

It is super useful, but today it went offline due to a Cloudflare bug. :-(

Glad I found Vector-Vein, but you guys should check it out if you have time. It has some very powerful features implemented as either control flows or primitive commands, which are not available elsewhere.
