### ISSUE TITLE
升级V0.2.10,  gemini 无法使用

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#67]
Qwen 是好的， Gemini不行， 其他还没一一测试。

![image](https://github.com/user-attachments/assets/70b259b4-8174-428a-9673-3a9841af38fe)

**Comment by AndersonBY** [comment]
https://github.com/AndersonBY/vector-vein/releases/download/v0.2.11/vector-vein-windows-v0.2.11.zip

修复好了

**Comment by suepradun** [comment]
> https://github.com/AndersonBY/vector-vein/releases/download/v0.2.11/vector-vein-windows-v0.2.11.zip
> 
> 修复好了

确认 ok。
