### ISSUE TITLE
A deadloop occurs when the agent calls the workflow.

### ISSUE THREAD

**Issue by xeon-ye** [AndersonBY/vector-vein#74]
![1734514102528](https://github.com/user-attachments/assets/0889c631-f7cf-41ec-b329-4d1b6c973011)

**Comment by AndersonBY** [comment]
看看日志里怎么写的

**Comment by xeon-ye** [comment]
thx,I will analyze the codes

**Comment by xeon-ye** [comment]
App runs like a charm when I change the model with 'moonshot'
