### ISSUE TITLE
在设置中无法为gemini 添加模型也无法读取模型列表，使其无法使用gemini2.0

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#75]
![image](https://github.com/user-attachments/assets/cc85bcb1-46df-4028-a778-650a2d25e6c3)

**Comment by AndersonBY** [comment]
https://github.com/AndersonBY/vector-vein/releases/tag/v0.3.4

最新版修复了

**Comment by suepradun** [comment]
更新为 0.3.4后，设置面板已经出现了新的模型。

但是在模型组件界面却没有出现新的选项。
![image](https://github.com/user-attachments/assets/296fadba-99a8-45b0-bdd2-b87a43255bb9)

**Comment by AndersonBY** [comment]
重新上传了一下，https://github.com/AndersonBY/vector-vein/releases/tag/v0.3.4

之前前端资源没用最新的编译。

**Comment by suepradun** [comment]
测试通过，感谢。

不过，2.0 现在好像只支持8K， 系统默认32K是跑不了的，需要手动修改后才能跑。
![image](https://github.com/user-attachments/assets/a30911be-ec8e-4c9f-ab45-ec96f1f7cf76)

**Comment by AndersonBY** [comment]
不应该吧，应该100万才对，你看看你那边报错是啥。我这边是正常的。

![image](https://github.com/user-attachments/assets/de13ea79-ed1a-4e35-8f8a-0c9892e29cc4)
